version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build phase....
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo Building the project...
      - mvn clean package
      - echo "Listing target directory after build"
      - ls -R target
  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed.
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
